baseurl: "/"
title: "Phantom"
main_js: "assets/js/main.js"
params:
  header:
    logo_img_src: images/logo.svg
  contact:
    enabled: true
    title: Get in touch
  social:
    enabled: true
    title: Follow
    follow_section:
      - title: Twitter
        icon: fa-twitter
        link_url: "#"
      - title: Facebook
        icon: fa-facebook
        link_url: "#"
      - title: Instagram
        icon: fa-instagram
        link_url: "#"
      - title: Dribbble
        icon: fa-dribbble
        link_url: "#"
      - title: GitHub
        icon: fa-github
        link_url: "#"
      - title: 500px
        icon: fa-500px
        link_url: "#"
      - title: Phone
        icon: fa-phone
        link_url: "#"
      - title: Email
        icon: fa-envelope-o
        link_url: "#"
sass:
  input_file: sass/main.scss
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
#templates:
#  body_class: "is-preload"
